dist: trusty

sudo: required

jdk:
  - oraclejdk8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - gcc-5
      - g++-5

before_install:
  - sudo apt-get purge openjdk-9* oracle-java9*
  - sudo apt-get install maven

script:
  - mvn package test